### PR TITLE
Fix for https://github.com/idangozlan/verdaccio-bitbucket/issues/18

### PR DESCRIPTION
**Pull request by AceVentura**
The npm publish command will build the files to the lib folder and ignore the src folder.

### CODE REVIEW

**Comment by idangozlan** [comment]
Please change to PR to merge to `develop` branch.

**Comment by jdecoster** [comment]
@idangozlan @AceVentura any update on this ?

**Comment by AceVentura** [comment]
@jdecoster waiting for @idangozlan  to accept the pull request.

**Comment by idangozlan** [comment]
merged. will release new version now.

**Pull request merged**
